<a href="https://colab.research.google.com/github/hiuk21/new-project/blob/main/4%EC%A3%BC%EC%B0%A8%EC%8B%A4%EC%8A%B5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
#안녕하세요
##안녕하세요
###안녕하세요
####안녕하세요

SyntaxError: invalid syntax (2347570092.py, line 6)

#안녕하세요
##안녕하세요
###안녕하세요
####안녕하세요

**혼공분석**

*혼공분석*

>홍공분석

_혼공분석_

*혼공분석
- 혼공분석

[한빛미디어](http://www.hanbit.co.kr/)

$y = x / times z$

seconds_in_a_week = 24*60*60*7
seconds_in_a_week

# *새 섹션*

In [2]:
seconds_in_a_week = 24*60*60*7
seconds_in_a_week

604800

# 새 섹션

In [3]:
import gdown
gdown.download('https://bit.ly/3eecMKZ',
               '남산도서관 장서 대출목록 (2026년 02월).csv', quiet = False)

Downloading...
From: https://bit.ly/3eecMKZ
To: /content/남산도서관 장서 대출목록 (2026년 02월).csv
100%|██████████| 58.1M/58.1M [00:00<00:00, 252MB/s]

'남산도서관 장서 대출목록 (2026년 02월).csv'

In [4]:
with open('남산도서관 장서 대출목록 (2026년 02월).csv') as f:
  print(f.readline())

UnicodeDecodeError: 'utf-8' codec can't decode byte 0xb9 in position 0: invalid start byte

In [7]:
import chardet
with open('남산도서관 장서 대출목록 (2026년 02월).csv', mode = 'rb') as f:
  d = f.readline()
print(chardet.detect(d))

{'encoding': 'EUC-KR', 'confidence': 0.99, 'language': 'Korean'}

In [9]:
with open('남산도서관 장서 대출목록 (2026년 02월).csv', encoding= 'EUC-KR') as f:
  print(f.readline())
  print(f.readline())

번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,

"1","인공지능과 흙","김동훈 지음","민음사","2021","9788937444319","","","","","1","0","2021-03-19",

In [10]:
import pandas as pd
df = pd.read_csv('남산도서관 장서 대출목록 (2026년 02월).csv', encoding= 'EUC-KR')

/tmp/ipykernel_1807/3941834297.py:2: DtypeWarning: Columns (5,6,9) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('남산도서관 장서 대출목록 (2026년 02월).csv', encoding= 'EUC-KR')

In [11]:
df.head()

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [12]:
df.to_csv('ns_202602.csv')

In [13]:
with open('ns_202602.csv') as f:
  for i in range(3):
    print(f.readline(), end='')

,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,,,,,1,0,2021-03-19,
1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,,,,,1,0,2021-03-19,

In [14]:
ns_df = pd.read_csv('ns_202602.csv', low_memory=False)
ns_df.head()

,Unnamed: 0,번호,도서명,저자,출판사,발행년도,ISBN,세트 ISBN,부가기호,권,주제분류번호,도서권수,대출건수,등록일자,Unnamed: 13
0,0,1,인공지능과 흙,김동훈 지음,민음사,2021,9788937444319,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
1,1,2,가짜 행복 권하는 사회,김태형 지음,갈매나무,2021,9791190123969,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
2,2,3,나도 한 문장 잘 쓰면 바랄 게 없겠네,김선영 지음,블랙피쉬,2021,9788968332982,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
3,3,4,예루살렘 해변,"이도 게펜 지음, 임재희 옮김",문학세계사,2021,9788970759906,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN
4,4,5,김성곤의 중국한시기행 : 장강·황하 편,김성곤 지음,김영사,2021,9788934990833,NaN,NaN,NaN,NaN,1,0,2021-03-19,NaN

In [15]:
d = {"name": "혼자 공부하는 데이터 분석"}
print(d['name'])

혼자 공부하는 데이터 분석

<혼자 공부하는 데이터 분석>이라는 도서명을 JSON 객체로 나타내면 다음과 같이 중괄호를 사용하고
파이썬의 딕셔너리와 비슷하게 키key와 값value을 콜론(:)으로 연결

도서명에 해당하는 키는 "name"으로 정하고, 키와 값에 문자열을 쓰려면 항상 큰따옴표(" ")로 감싸 주어야 함

In [3]:
import json

In [19]:
d_str = json.dumps(d, ensure_ascii= False)
print(d_str)

{"name": "혼자 공부하는 데이터 분석"}

json.dumps()함수를 사용하면 앞에서 만든 딕셔너리 d를 문자열로 변환

- ensure()_ascii매개변수를 False로 지정한 이유: 딕셔너리 d에 한글이 포함되어있기 때문

In [20]:
print(type(d_str))

<class 'str'>

딕셔너리가 문자열로 제대로 바뀐지 확인

In [21]:
d2 = json.loads(d_str)
print(d2['name'])

혼자 공부하는 데이터 분석

json.loads() 함수
- JSON 문자열을 파이썬 객체로 변환

In [22]:
print(type(d2))

<class 'dict'>

문자열이 파이썬 딕셔너리로 바뀌었는지 확인

In [23]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022}')
print(d3['name'])
print(d3['author'])
print(d3['year'])

혼자 공부하는 데이터 분석
박해선
2022

여러 개의 항목이 들어 있는 딕셔너리나, 딕셔너리 안에 리스트를 포함

도서명외에 저자와 발행 연도 추가

- 앞에서는 딕셔너리 먼저 만들고 json.dumps()함수로 문자열 변환한 다음 jason.loads()함수 사용

but 매번 이렇게 하면 번거로우니 json.loads() 함수에 직접 전달

In [26]:
d3 = json.loads('{"name": "혼자 공부하는 데이터 분석", "author": ["박해선", "홍길동"], "year": 2022}')
print(d3['author'] [1])

홍길동

json 은 대괄호 안에 여러 항목을 나열하여 배열을 표현할 수 있음(리스트와 비슷)

In [7]:
d4_str = """
[
  {"name": "혼자 공부하는 데이터 분석", "author": "박해선", "year": 2022},
  {"name": "혼자 공부하는 머신러닝+딥러닝", "author": "박해선", "year":2020}
]
"""
d4 = json.loads(d4_str)
print(d4[0]['name'])

혼자 공부하는 데이터 분석

In [9]:
import pandas as pd
pd.read_json(d4_str)

/tmp/ipykernel_714/1308304786.py:2: FutureWarning: Passing literal json to 'read_json' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_json(d4_str)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

read_json()함수
- 문자열을 데이터프레임으로

In [10]:
pd.DataFrame(d4)

               name author  year
0    혼자 공부하는 데이터 분석    박해선  2022
1  혼자 공부하는 머신러닝+딥러닝    박해선  2020

데이터프레임으로 바꾸는 또 다른 방법

In [11]:
x_str = """
<book>
    <name> 혼자 공부하는 데이터 분석 </name>
    <author> 박해선 </author>
    <year> 2022 </year>
</book>
"""

먼저 xml 문자열을 x_str 변수에 저장

In [13]:
import xml.etree.ElementTree as et
book = et.fromstring(x_str)

xml.etree.ElemenTree 모듈의 fromstring()함수를 사용해 x_str 문자열을 파이썬 객체로 변환

In [14]:
print(type(book))

<class 'xml.etree.ElementTree.Element'>

type( ) 함수로 fromstring( ) 함수가 어떤 객체를 반환하는지 book 변수의 타입을 확인

In [15]:
print(book.tag)

book

book 객체의 tag 속성을 출력하여 엘리먼트 이름 확인

In [16]:
book_childs = list(book)
print(book_childs)

[<Element 'name' at 0x7cb00b8322a0>, <Element 'author' at 0x7cb00b833b00>, <Element 'year' at 0x7cb00b833c40>]

In [17]:
name, author, year = book_childs
print(name.text)
print(author.text)
print(year.text)

 혼자 공부하는 데이터 분석
 박해선
 2022

In [18]:
name = book.findtext('name')
author = book.findtext('author')
year = book.findtext('year')
print(name)
print(author)
print(year)

 혼자 공부하는 데이터 분석
 박해선
 2022

book 객체의 findtext( ) 메서드를 사용하면 해당하는 자식 엘리먼트를 탐색하여 자동으로 텍스트를 반환

In [19]:
x2_str = """
<books>
    <book>
        <name> 혼자 공부하는 데이터 분석 </name>
        <author> 박해선 </author>
        <year> 2022 </year>
    </book>
    <book>
        <name> 혼자 공부하는 머신러닝 + 딥러닝 </name>
        <author> 박해선 </author>
        <year> 2020 </year>
    </book>
</books>
"""

In [21]:
books = et.fromstring(x2_str)
print(books.tag)

books

In [22]:
for book in books.findall('book'):
  name = book.findtext('name')
  author = book.findtext('author')
  year = book.findtext('year')
  print(name)
  print(author)
  print(year)
  print()

 혼자 공부하는 데이터 분석
 박해선
 2022

 혼자 공부하는 머신러닝 + 딥러닝
 박해선
 2020

In [23]:
pd.read_xml(x2_str)

/tmp/ipykernel_714/212699965.py:1: FutureWarning: Passing literal xml to 'read_xml' is deprecated and will be removed in a future version. To read from a literal string, wrap it in a 'StringIO' object.
  pd.read_xml(x2_str)

                   name author  year
0       혼자 공부하는 데이터 분석    박해선   2022
1   혼자 공부하는 머신러닝 + 딥러닝    박해선   2020